// Copyright 2016 Mender Software AS
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
package mocks

import client "github.com/mendersoftware/deviceauth/client"
import context "context"
import mock "github.com/stretchr/testify/mock"
import tenant "github.com/mendersoftware/deviceauth/client/tenant"

// ClientRunner is an autogenerated mock type for the ClientRunner type
type ClientRunner struct {
	mock.Mock
}

// VerifyToken provides a mock function with given fields: ctx, token, _a2
func (_m *ClientRunner) VerifyToken(ctx context.Context, token string, _a2 client.HttpRunner) error {
	ret := _m.Called(ctx, token, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.HttpRunner) error); ok {
		r0 = rf(ctx, token, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

var _ tenant.ClientRunner = (*ClientRunner)(nil)
