// Copyright 2016 Mender Software AS
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// generated with:
// mockery -name=InventoryClient  -inpkg -print

package main

import log "github.com/mendersoftware/deviceauth/log"
import mock "github.com/stretchr/testify/mock"
import requestid "github.com/mendersoftware/deviceauth/requestid"

// MockInventoryClient is an autogenerated mock type for the InventoryClient type
type MockInventoryClient struct {
	mock.Mock
}

// AddDevice provides a mock function with given fields: dev, client
func (_m *MockInventoryClient) AddDevice(dev *Device, client requestid.ApiRequester) error {
	ret := _m.Called(dev, client)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Device, requestid.ApiRequester) error); ok {
		r0 = rf(dev, client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UseLog provides a mock function with given fields: l
func (_m *MockInventoryClient) UseLog(l *log.Logger) {
	_m.Called(l)
}

var _ InventoryClient = (*MockInventoryClient)(nil)
