FROM golang:1.16.5-alpine3.12 as builder
WORKDIR /go/src/github.com/mendersoftware/deviceauth
COPY ./ .
RUN env CGO_ENABLED=0 go test -c -o deviceauth -tags main \
    -coverpkg $(go list ./... | grep -v vendor | grep -v mock | grep -v test | tr  '\n' ,)

FROM scratch
EXPOSE 8080

COPY  --from=builder /go/src/github.com/mendersoftware/deviceauth/deviceauth /usr/bin/
COPY ./config.yaml /etc/deviceauth/
ENTRYPOINT ["/usr/bin/deviceauth", "--config", "/etc/deviceauth/config.yaml"]

STOPSIGNAL SIGINT
