#!/bin/bash

set -e

SELFDIR=$(readlink -f $(dirname $0))

usage() {
    echo "usage: $(basename $0) <path-to-integration> <path-to-acceptance-compose-file>]"
    echo
    echo "  Sets up acceptance tests environment and runs tests defined"
    echo "  in directory:"
    echo "     $SELFDIR"
    echo
    echo "Environment variables:"
    echo "   NO_CLEANUP - test environment will not be removed if NO_CLEANUP"
    echo "                is not empty"

}

[ "$1" = "-h" -o "$1" = "--help" ] && {
    usage
    exit 0
}

INTEGRATION_PATH=$1

[ -z "$INTEGRATION_PATH" -o ! -d "$INTEGRATION_PATH" ] && {
    echo "integration repository path not provided"
    usage
    exit 1
}
shift

TESTS_COMPOSE_PATH=$1

[ -z "$TESTS_COMPOSE_PATH" -o ! -f "$TESTS_COMPOSE_PATH" ] && {
    echo "tests compose path not provided"
    usage
    exit 1
}
shift

COMPOSE_CMD="docker-compose -p acceptance-tests -f $INTEGRATION_PATH/docker-compose.yml"
TEST_SERVICE=${TEST_SERVICE:-"acceptance"}

# start acceptance tests container
$COMPOSE_CMD -f $TESTS_COMPOSE_PATH run ${TEST_SERVICE} || failed=1

# fold everything
[ -z "$NO_CLEANUP" ] && $COMPOSE_CMD down || true

exit $failed
