// Copyright 2017 Northern.tech AS
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
package mocks

import apiclient "github.com/mendersoftware/go-lib-micro/apiclient"
import context "context"
import deviceadm "github.com/mendersoftware/deviceauth/client/deviceadm"
import mock "github.com/stretchr/testify/mock"

// ClientRunner is an autogenerated mock type for the ClientRunner type
type ClientRunner struct {
	mock.Mock
}

// AddDevice provides a mock function with given fields: ctx, req, client
func (_m *ClientRunner) AddDevice(ctx context.Context, req deviceadm.AdmReq, client apiclient.HttpRunner) error {
	ret := _m.Called(ctx, req, client)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, deviceadm.AdmReq, apiclient.HttpRunner) error); ok {
		r0 = rf(ctx, req, client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

var _ deviceadm.ClientRunner = (*ClientRunner)(nil)
