swagger: '2.0'
info:
  title: Authentication Service Device API
  version: '0.1'

host: 'localhost:8080'
basePath: '/api/devices/0.1/authentication'

paths:
  /auth_requests:
    post:
      summary: Submit a device authentication request.
      description: |
        The device passes its vendor-defined identification data and tenant token
        to obtain a valid JSON Web Token to be used in subsequent Mender API communications.
        The id data is encrypted using the tenant's public key.

        The Identity Service consults the id data with the Device Admission Service,
        and either accepts the request, issuing a JWT (if the identity has been
        accepted by the user), or rejects it as unauthorized.

        This method simultaneously acts as a bootstraping one - upon the first
        auth request, the device is enrolled in the system, and we start
        tracking its state via generated Device ID.

        The returned JWT is
          * signed with the identity service's private key
          * encrypted with the device's public key

        JWTs are issued with the following standard fields:
          * 'exp' - expiry date
          * 'sub' - subject (Mender-generated device ID)
          * 'jit' - token's unique identifier

        Each request is signed with the device's private key. The 'X-MEN-Signature' custom header carries the signature computed as:

           BASE64(SIGN(privkey, SHA256(body)))

        An increasing 'seq_no' is used to prevent replay attacks. Upon the very first request
        the client can provide any non-zero uint64, which will be recorded by the server for subsequent requests.

      parameters:
        - name: auth_request
          in: body
          description: Auth request
          required: true
          schema:
            $ref: "#/definitions/AuthRequestNew"
        - name: X-MEN-Signature
          in: header
          type: string
          description: Base64 version of body signed with device's private key.
      responses:
        200:
          description: Authentication successful - a new JWT is issued and returned
                       (encrypted with device's public key).
          schema:
            type: number
            format: binary
        401:
          description: The device cannot be granted authentication (e.g. not accepted
                       by the user yet, or explicitly rejected).
        400:
          description: Missing/malformed request params or body.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  AuthRequestNew:
    type: object
    properties:
      id_data:
        type: string
        description: Vendor-specific JSON representation of device identity, encrypted
                     with the tenant's public key.

                     In reference implementation, it is a JSON structure
                     with vendor-selected fields, such as MACs, serial numbers, etc.
      tenant_token:
        type: string
        description: A tenant's unique token (issued by Mender via web GUI/API).
      pubkey:
        type: string
        description: The device's public key, generated by the device or pre-provisioned by the vendor.
    required:
      - id_data
      - tenant_token
      - pubkey
  Error:
    description: Error descriptor
    type: object
    properties:
      error:
        description: Description of the error
        type: string
