// Copyright 2017 Northern.tech AS
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
package mocks

import jwt "github.com/mendersoftware/deviceauth/jwt"
import log "github.com/mendersoftware/go-lib-micro/log"
import mock "github.com/stretchr/testify/mock"
import model "github.com/mendersoftware/deviceauth/model"

// JWTAgentApp is an autogenerated mock type for the JWTAgentApp type
type JWTAgentApp struct {
	mock.Mock
}

// GenerateTokenSignRS256 provides a mock function with given fields: devId
func (_m *JWTAgentApp) GenerateTokenSignRS256(devId string) (*model.Token, error) {
	ret := _m.Called(devId)

	var r0 *model.Token
	if rf, ok := ret.Get(0).(func(string) *model.Token); ok {
		r0 = rf(devId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(devId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UseLog provides a mock function with given fields: l
func (_m *JWTAgentApp) UseLog(l *log.Logger) {
	_m.Called(l)
}

// ValidateTokenSignRS256 provides a mock function with given fields: token
func (_m *JWTAgentApp) ValidateTokenSignRS256(token string) (string, error) {
	ret := _m.Called(token)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ jwt.JWTAgentApp = (*JWTAgentApp)(nil)
